branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: rio
  default_ec2_keyname: mbucci
  default_platform: Python 2.7
  default_region: us-east-1
  profile: null
  sc: git
