"""empty message

Revision ID: 2bd2c323c61f
Revises: None
Create Date: 2016-12-14 21:52:49.964340

"""

# revision identifiers, used by Alembic.
revision = '2bd2c323c61f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rio_trade',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('desination', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('customs_unit_boarding_id', sa.Integer(), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('transaction_amount_wt', sa.Float(), nullable=True),
    sa.Column('transaction_amount_usd', sa.Float(), nullable=True),
    sa.Column('transacted_product_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rio_trade_kind'), 'rio_trade', ['kind'], unique=False)
    op.create_index(op.f('ix_rio_trade_month'), 'rio_trade', ['month'], unique=False)
    op.create_index(op.f('ix_rio_trade_year'), 'rio_trade', ['year'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rio_trade_year'), table_name='rio_trade')
    op.drop_index(op.f('ix_rio_trade_month'), table_name='rio_trade')
    op.drop_index(op.f('ix_rio_trade_kind'), table_name='rio_trade')
    op.drop_table('rio_trade')
    ### end Alembic commands ###
