"""Initial Tables

Revision ID: 41cc315cdaf7
Revises: None
Create Date: 2016-02-10 22:09:03.161524

"""

# revision identifiers, used by Alembic.
revision = '41cc315cdaf7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_contests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(length=255), nullable=True),
    sa.Column('product_required', sa.Boolean(), nullable=True),
    sa.Column('splash_page_url', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    )
    op.create_table('pr_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.Text(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contests',
    sa.Column('contest_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['pr_contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pr_users.id'], ),
    sa.UniqueConstraint('contest_id', 'user_id')
    )
    op.create_table('pr_videos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('contest_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['pr_contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pr_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_views',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pr_users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['pr_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_votes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pr_users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['pr_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.BigInteger(), nullable=True),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['pr_tags.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['pr_videos.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('pr_votes')
    op.drop_table('pr_views')
    op.drop_table('pr_videos')
    op.drop_table('contests')
    op.drop_table('pr_users')
    op.drop_table('pr_tags')
    op.drop_table('pr_contests')
    ### end Alembic commands ###
