"""empty message

Revision ID: d75aa82c44d9
Revises: 2bd2c323c61f
Create Date: 2016-12-16 19:50:07.127058

"""

# revision identifiers, used by Alembic.
revision = 'd75aa82c44d9'
down_revision = '2bd2c323c61f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rio_brazil_lookup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.String(length=2), nullable=False),
    sa.Column('mesoregion_id', sa.Integer(), nullable=True),
    sa.Column('microregion_id', sa.Integer(), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255, collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'region_id', 'state_id')
    )
    op.create_table('rio_product_lookup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_group', sa.Integer(), nullable=True),
    sa.Column('product_specific', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=255, collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'product_type', 'product_id')
    )
    op.create_table('rio_world_lookup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=255, collation='utf8_unicode_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rio_world_lookup')
    op.drop_table('rio_product_lookup')
    op.drop_table('rio_brazil_lookup')
    ### end Alembic commands ###
